# Generated by Django 4.2.7 on 2024-02-06 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_expiration_date_alter_user_referral_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 1, 21, 24, 190912), verbose_name='Код действителен до'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=5241713, max_length=7, verbose_name='Ваш реферальный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referrals',
            field=models.TextField(default='-', verbose_name='Мои рефералы'),
        ),
    ]
